name: Render Menu

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Playwright browsers
        uses: actions/cache@v5
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Installa dipendenze Python
        run: pip install -r requirements.txt

      - name: Installa dipendenze sistema Playwright
        run: playwright install-deps chromium

      - name: Installa Playwright + Chromium
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: playwright install chromium

      - name: Esegui script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_DEV }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY_DEV }}
          MENUS_FILE: config/menus_dev.csv
          SUPABASE_BUCKET: menus
        run: python menu_export.py